# Generated by Django 2.2.6 on 2019-11-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='movie_image')),
                ('block_explain', models.TextField(verbose_name='Explain of Movie')),
                ('rating', models.FloatField(default=0.0)),
                ('numberOfClicks', models.IntegerField(default=0)),
                ('article_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
