# Generated by Django 2.2.6 on 2019-11-17 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='movie name'),
            preserve_default=False,
        ),
    ]
