# Generated by Django 2.2.6 on 2019-11-18 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_block_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='jenre',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='movie jenre'),
            preserve_default=False,
        ),
    ]
