# Generated by Django 2.2.6 on 2019-11-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_block_jenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=200, verbose_name='Na me of article'),
        ),
    ]
