# Generated by Django 2.2.6 on 2019-11-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20191123_2222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
