# Generated by Django 2.2.6 on 2019-11-24 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0008_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='movie_trailer_url',
            field=models.CharField(default='https://www.youtube.com/embed/L0ttxMz-tyo', max_length=100, verbose_name='movie_trailer'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(verbose_name='Date of set')),
                ('comment_text', models.TextField(max_length=200, verbose_name='Text')),
                ('of_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Block')),
                ('of_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
