# Generated by Django 2.2.6 on 2019-11-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20191124_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
