# Generated by Django 2.2.6 on 2019-11-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_heiter',
            field=models.BooleanField(default=True),
        ),
    ]
