# Generated by Django 2.2.6 on 2019-11-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_comment_is_heiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='movie_cinema',
            field=models.ManyToManyField(to='article.Cinema'),
        ),
        migrations.AddField(
            model_name='block',
            name='movie_price',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinema',
            name='cinema_movie_discouns',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
