# Generated by Django 2.2.6 on 2019-11-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_block_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='movie_poster_img_url',
            field=models.CharField(default='https://www.youtube.com/embed/L0ttxMz-tyo', max_length=100),
        ),
    ]
