# Generated by Django 2.2.6 on 2019-12-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_block_movie_poster_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='movie_poster_img_url',
            field=models.CharField(default='http://thumbs.dfs.ivi.ru/storage4/contents/8/5/25df26b4ff265c284df18453f62ac7.jpg', max_length=100),
        ),
    ]
