# Generated by Django 2.2.6 on 2019-12-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20191202_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='movie_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
