# Generated by Django 2.2.6 on 2019-12-02 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_block_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_x', models.PositiveIntegerField()),
                ('cor_y', models.PositiveIntegerField()),
                ('status', models.BooleanField()),
                ('of_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Room')),
            ],
        ),
    ]
