# Generated by Django 2.2.6 on 2019-12-02 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of shop'),
            preserve_default=False,
        ),
    ]
