# Generated by Django 2.2.6 on 2019-12-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_shop_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='cinema_poster',
            field=models.CharField(default='http://thumbs.dfs.ivi.ru/storage4/contents/8/5/25df26b4ff265c284df18453f62ac7.jpg', max_length=100),
        ),
    ]
