# Generated by Django 2.2.6 on 2019-12-03 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_cinema_cinema_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='of_movie',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='article.Block'),
            preserve_default=False,
        ),
    ]
