# Generated by Django 2.2.6 on 2019-12-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_room_of_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='cinema_movie_discouns',
            field=models.FloatField(),
        ),
    ]
